### PR TITLE
DES-882: Modal now resizes when browser is resized

### PR DESCRIPTION
**Pull request by briandunnpearson**

### CODE REVIEW

**Comment by briandunnpearson** [comment]
Setting { 'leading': true } did not help in this case of resizing.

**Comment by briandunnpearson** [comment]
Ready for QA or something 😃

**Comment by briandunnpearson** [comment]
@JasonLantz  Eajaz discovered that the demo was not working in IE 11.  This was due to webpack-dev-server 2.11.x having a dependency on strip-ansi 4.0, which used arrow functions, which are not supported in IE 11.  For a quick fix, I pinned the webpack-dev-server at 2.9.x, which uses strip-ansi 3.x.  Read all about it here: https://github.com/webpack/webpack-dev-server/issues/1278.  Here is a possible PR for webpack-dev-server to resolve this issue: https://github.com/webpack/webpack-dev-server/pull/1273

**Comment by umahaea** [comment]
all approved. merging it.

**Pull request merged**
