### PR TITLE
custom Styles and ClassNames support added to Modal.

### PR DESCRIPTION
**Pull request by MVSTEJA**
PDA Team,

I have made changes to add custom classsNames, Styles based on react-modal and custom footer of modal. Kindly let me know, if i coded in somewhere wrongly.

### CODE REVIEW

**Comment by JasonLantz** [comment]
Hey surya,
just curious on 2 things....
1) do you have a design that requires the changes that you requested....
2) what's up with the !! on line 41 of modal.js, looks like you could remove that and it would work just fine...

**Comment by MVSTEJA** [comment]
@JasonLantz ,

Implementing Modal from the repo gave me something like this :-  

pearsonstyles

But what i was expecting it to do is this :- 

presentdesign

And this is from our zeplin designs :- 

edituserstudentoptout 3x

**Comment by MVSTEJA** [comment]
And yes line 41 truthy check is unnecessary, made another commit to the PR.

**Comment by wyseguyonline** [comment]
I am hesitant to approve an approach that allows consuming teams to input styles directly into the component to override the existing styles.  This will introduce variability into this component that our team couldn't begin to predict, let alone support.  Worse, an implementation like this will undermine the effort to provide a consistent look and feel for all apps built with our components.  

I would encourage your designers to contact the design team (name provided in HipChat help room) that we work with and see about reconciling the two modal designs.  I would rather see consistency among apps our company delivers than the degree of variability allowing custom styling creates.

**Comment by mhomolak** [comment]
As the comments above have mentioned, we will not be moving forward with this pull request.  Our Modal was designed to match a specific design and a11y spec.  With the adding of custom styles this would allow deviation from that previously mentioned spec.

**Pull request closed without merging**
